### ISSUE TITLE
Redirects no longer working in mobile

### ISSUE THREAD

**Issue by RCatersels** [mendix/URLRedirector#2]
I was testing the mobile part of our model in Mx6.9.1 but I noticed that a redirect on IOS phones is no longer working (did not check android yet). Do you know of any issues due to IOS changes?

Regards,
Ronald

**Comment by riclo** [comment]
is this still the case ? my urlredirect  on the device  doesn't respond either

**Comment by RCatersels** [comment]
You might check your phonegap config.xml. I solved it by adding
	<gap:plugin name="cordova-plugin-whitelist" source="npm" version="1.3.2" />
	<allow-navigation href="https://someurl.mendixcloud.com/*" />

Regards,
Ronald

**Comment by JelteMX** [comment]
Added this to the documentation of the widget, see [commit](https://github.com/mendix/URLRedirector/commit/e32682fe8ba27a6aa9539ddf40cb88e40bbe4b04)
